/**
 * Lab registry - source of truth for Available Labs.
 * Aligned with docs/*.md. Each lab has step-by-step instructions for Docker-first deployment.
 */

export const LABS = [
  {
    id: 'ransomware-investigation',
    title: 'Ransomware Investigation',
    doc: 'RANSOMWARE_INVESTIGATION_LAB',
    duration: '60-90 min',
    difficulty: 'Intermediate',
    terminalsNeeded: 2,
    roles: 'Investigator (student)',
    description: 'Trace a simulated ransomware payment through tumblers. Enter findings to validate against the scenario.',
    steps: [
      { terminal: 1, title: 'Enter container', instruction: 'Open a terminal and enter the Docker container.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 1, title: 'Go to CLI labs', instruction: 'Navigate to the forensics scripts.', code: 'cd /app/scripts/cli-labs/standalone' },
      { terminal: 1, title: 'Generate scenario (required)', instruction: 'Run setup first — the blockchain starts fresh each docker-compose up. This creates the victim, attacker, and tumbler addresses.', code: 'cd /app/scripts/cli-labs/standalone\nnode forensics-setup.js' },
      { terminal: 1, title: 'Run the lab', instruction: 'Launch the guided investigation lab.', code: 'cd /app/scripts/cli-labs/standalone\nnode 6-ransomware-investigation.js' },
      { terminal: 2, title: 'Open second terminal', instruction: 'Open a second terminal window for the Hardhat console (investigation commands).', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 2, title: 'Start Hardhat console', instruction: 'Use this terminal to run investigation commands when the lab prompts you.', code: 'npm run console' },
    ],
    nuance: 'You need TWO terminals: one for the lab prompts, one for running investigation commands. Switch between them as the lab directs.',
  },
  {
    id: 'ransomware-advanced',
    title: 'Ransomware Investigation (Advanced)',
    doc: 'RANSOMWARE_ADVANCED_LAB',
    duration: '90-120 min',
    difficulty: 'Intermediate',
    terminalsNeeded: 2,
    roles: 'Investigator (student)',
    description: 'Trace a multi-victim ransomware attack through a complex tumbler network. Builds on the basic lab.',
    steps: [
      { terminal: 1, title: 'Enter container', instruction: 'Open a terminal and enter the Docker container.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 1, title: 'Go to CLI labs', instruction: 'Navigate to the forensics scripts.', code: 'cd /app/scripts/cli-labs/standalone' },
      { terminal: 1, title: 'Generate advanced scenario (required)', instruction: 'Run setup first — creates 3 victims, multiple tumblers, and convergence points.', code: 'cd /app/scripts/cli-labs/standalone\nnode forensics-setup-advanced.js' },
      { terminal: 1, title: 'Run the advanced lab', instruction: 'Launch the multi-victim investigation.', code: 'cd /app/scripts/cli-labs/standalone\nnode 7-ransomware-advanced.js' },
      { terminal: 2, title: 'Open second terminal', instruction: 'Open a second terminal for the Hardhat console.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 2, title: 'Start Hardhat console', instruction: 'Use for investigation commands when prompted.', code: 'npx hardhat console --network localhost' },
    ],
    nuance: 'Two terminals required. Complete the basic Ransomware Investigation lab first.',
  },
  {
    id: 'house-sale',
    title: 'House Sale',
    doc: 'HOUSE_SALE_LAB',
    duration: '45-60 min',
    difficulty: 'Intermediate',
    terminalsNeeded: 3,
    roles: 'Admin, Seller (John), Buyer (Mark)',
    description: 'Simulate a real estate transaction. Three participants: Admin deploys, Seller and Buyer complete the escrow flow.',
    steps: [
      { terminal: 1, title: 'Admin: Enter container', instruction: 'Admin opens first terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 1, title: 'Admin: Deploy contract', instruction: 'Use CLI Contract Builder to deploy House Sale.', code: 'cd /app/scripts/cli-labs/standalone\nnode interactive.js\n# Select: 9. Contract Builder Lab → 1. House Sale' },
      { terminal: 2, title: 'Seller (John): Enter container', instruction: 'John opens a second terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 2, title: 'Seller: Open Hardhat console', instruction: 'John connects with his wallet.', code: 'npm run console' },
      { terminal: 3, title: 'Buyer (Mark): Enter container', instruction: 'Mark opens a third terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 3, title: 'Buyer: Open Hardhat console', instruction: 'Mark connects with his wallet.', code: 'npx hardhat console --network localhost' },
      { shared: true, title: 'Follow the lab flow', instruction: 'Admin shares contract address. John and Mark each create their OWN contract instance connected to their wallet. Follow the escrow steps: deposit → inspection → balance → confirm.' },
    ],
    nuance: 'THREE terminals (or three people with separate terminals). Each participant must create their own contract instance — do not share the same instance.',
  },
  {
    id: 'vehicle-title',
    title: 'Vehicle Title',
    doc: 'VEHICLE_TITLE_LAB',
    duration: '30-45 min',
    difficulty: 'Beginner',
    terminalsNeeded: 2,
    roles: 'Admin (DMV), Owners (students)',
    description: 'Register a vehicle title and transfer ownership. Learn asset provenance and ownership chains.',
    steps: [
      { terminal: 1, title: 'Admin: Enter container', instruction: 'Admin opens first terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 1, title: 'Admin: Deploy via CLI', instruction: 'Use Contract Builder → Vehicle Title Transfer.', code: 'cd /app/scripts/cli-labs/standalone\nnode interactive.js\n# Select: 9. Contract Builder Lab → 2. Vehicle Title Transfer' },
      { terminal: 2, title: 'Owner: Enter container', instruction: 'Each participant opens their own terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 2, title: 'Owner: Hardhat console', instruction: 'Connect and create contract instance with your wallet.', code: 'npm run console' },
    ],
    nuance: 'Multiple participants: open separate terminals with docker-compose exec for each (Admin, Owner 1, Owner 2, etc.).',
  },
  {
    id: 'event-tickets',
    title: 'Event Tickets',
    doc: 'EVENT_TICKETS_LAB',
    duration: '30-45 min',
    difficulty: 'Beginner',
    terminalsNeeded: 2,
    roles: 'Organizer, Attendees',
    description: 'Sell and manage event tickets. Limited supply, transfers, check-in, and refunds on cancellation.',
    steps: [
      { terminal: 1, title: 'Organizer: Enter container', instruction: 'Organizer opens first terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 1, title: 'Organizer: Deploy via CLI', instruction: 'Use Contract Builder → Event Tickets.', code: 'cd /app/scripts/cli-labs/standalone\nnode interactive.js\n# Select: 9. Contract Builder Lab → 3. Event Tickets' },
      { terminal: 1, title: 'Dashboard', instruction: 'Open dashboard to monitor sales.', code: 'http://localhost:5173/dashboard.html' },
      { terminal: 2, title: 'Attendees: Enter container', instruction: 'Each attendee opens their own terminal (or uses web UI).', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 2, title: 'Attendees: Hardhat console', instruction: 'Buy tickets, transfer, etc.', code: 'npm run console' },
    ],
    nuance: 'Dashboard at /dashboard.html for monitoring. Attendees can also use the web interface if available.',
  },
  {
    id: 'voting-system',
    title: 'Voting System',
    doc: 'VOTING_SYSTEM_LAB',
    duration: '30-45 min',
    difficulty: 'Beginner',
    terminalsNeeded: 2,
    roles: 'Election Admin, Voters',
    description: 'Multi-option election with time-limited voting and automatic winner determination.',
    steps: [
      { terminal: 1, title: 'Admin: Enter container', instruction: 'Admin opens first terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 1, title: 'Admin: Deploy via CLI', instruction: 'Use Contract Builder → Voting System.', code: 'cd /app/scripts/cli-labs/standalone\nnode interactive.js\n# Select: 9. Contract Builder Lab → 4. Voting System' },
      { terminal: 1, title: 'Dashboard', instruction: 'Open dashboard for results.', code: 'http://localhost:5173/dashboard.html' },
      { terminal: 2, title: 'Voters: Enter container', instruction: 'Each voter opens their own terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 2, title: 'Voters: Hardhat console', instruction: 'Cast votes.', code: 'npm run console' },
    ],
    nuance: 'Dashboard at /dashboard.html for live results.',
  },
  {
    id: 'crowdfunding',
    title: 'Crowdfunding',
    doc: 'CROWDFUNDING_LAB',
    duration: '45-60 min',
    difficulty: 'Intermediate',
    terminalsNeeded: 2,
    roles: 'Creator, Contributors',
    description: 'Launch a crowdfunding campaign. Goal-based triggers, contributions, refunds if goal not met.',
    steps: [
      { terminal: 1, title: 'Creator: Enter container', instruction: 'Creator opens first terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 1, title: 'Creator: Deploy via CLI', instruction: 'Use Contract Builder → Crowdfunding.', code: 'cd /app/scripts/cli-labs/standalone\nnode interactive.js\n# Select: 9. Contract Builder Lab → 5. Crowdfunding Campaign' },
      { terminal: 1, title: 'Dashboard', instruction: 'Monitor campaign progress.', code: 'http://localhost:5173/dashboard.html' },
      { terminal: 2, title: 'Contributors: Enter container', instruction: 'Each contributor opens their own terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 2, title: 'Contributors: Hardhat console', instruction: 'Contribute ETH, claim refunds if failed.', code: 'npx hardhat console --network localhost' },
    ],
    nuance: 'Dashboard for progress. Contributors need ETH to contribute.',
  },
  {
    id: 'classroom-vote',
    title: 'Classroom Vote',
    doc: 'CLASSROOM_VOTE_LAB',
    duration: '30-45 min',
    difficulty: 'Beginner',
    terminalsNeeded: 2,
    roles: 'Instructor (deployer), Students (voters)',
    description: 'Live voting on a class question. Instructor deploys, students vote, results displayed on dashboard.',
    steps: [
      { terminal: 1, title: 'Instructor: Enter container', instruction: 'Instructor opens first terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 1, title: 'Instructor: Deploy via CLI', instruction: 'Use Contract Builder → Classroom Voting Demo.', code: 'cd /app/scripts/cli-labs/standalone\nnode interactive.js\n# Select: 9. Contract Builder Lab → 6. Classroom Voting Demo' },
      { terminal: 1, title: 'Dashboard', instruction: 'Display results to class.', code: 'http://localhost:5173/dashboard.html' },
      { terminal: 2, title: 'Students: Enter container', instruction: 'Each student opens their own terminal (or uses web).', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 2, title: 'Students: Hardhat console', instruction: 'Vote using wallet.', code: 'npm run console' },
    ],
    nuance: 'Share instructor IP so students access dashboard at http://<INSTRUCTOR-IP>:5173/dashboard.html',
  },
  {
    id: 'beacon-chain',
    title: 'Beacon Chain Lab',
    doc: 'BEACON_CHAIN_LAB',
    duration: '30-45 min',
    difficulty: 'Intermediate',
    terminalsNeeded: 1,
    roles: 'Instructor (starts session), Students (validators)',
    description: 'Interactive lab demonstrating committee formation, quorum, attestation, finality, and slashing. Students join, bots fill empty slots, blocks are produced automatically.',
    steps: [
      { terminal: 1, title: 'Deploy Beacon Lab', instruction: 'Run deploy script (chain must be running).', code: 'npm run deploy:beacon-lab' },
      { terminal: 1, title: 'Open Lab', instruction: 'Open the Beacon Chain Lab in the web app.', code: 'Click "Beacon Chain Lab" in sidebar (Learning mode)' },
      { shared: true, title: 'Students join', instruction: 'Students stake 32+ ETH to join. Can join anytime (lobby or during session).' },
      { shared: true, title: 'Instructor starts', instruction: 'Instructor clicks "Fill Bots and Start" (reserves slots for late joiners).' },
      { shared: true, title: 'Propose and attest', instruction: 'Blocks are produced automatically; students attest. Watch finality after 3 blocks.' },
    ],
    nuance: 'Share instructor IP so students access the lab. Finality: block N finalizes when block N+2 is justified.',
  },
  {
    id: 'token-concepts',
    title: 'Token Concepts (FT vs NFT)',
    doc: 'TOKEN_CONCEPTS_LAB',
    duration: '20-30 min',
    difficulty: 'Beginner',
    terminalsNeeded: 1,
    roles: 'Student (learner)',
    description: 'Learn fungible vs non-fungible tokens. Conceptual sections + optional hands-on deploy.',
    steps: [
      { terminal: 1, title: 'Enter container', instruction: 'Open a terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 1, title: 'Run Token Concepts', instruction: 'Run the interactive lab (or use Learn tab in web app).', code: 'cd /app/scripts/cli-labs/standalone\nnode 8-token-concepts.js' },
      { terminal: 1, title: 'Alternative: Interactive menu', instruction: 'Or launch from main menu.', code: 'cd /app/scripts/cli-labs/standalone\nnode interactive.js\n# Select: 13. Token Concepts (FT vs NFT)' },
    ],
    nuance: 'Sections 1–3 are conceptual. Section 4 offers hands-on deploy (browser or CLI).',
  },
  {
    id: 'contract-builder',
    title: 'Contract Builder Lab',
    doc: 'CONTRACT_BUILDER_LAB',
    duration: '30-45 min',
    difficulty: 'Beginner',
    terminalsNeeded: 1,
    roles: 'Deployer, Partner (two students)',
    description: 'Build a smart contract, deploy it to the chain, and use it with another student. Step-through flow with prebuilt scripts and terminal.',
    steps: [
      { terminal: 1, title: 'Open Contract Builder Lab', instruction: 'Go to Learning mode → Contract Builder Lab in sidebar.', code: 'http://localhost:5173/?view=contract-builder-lab' },
      { terminal: 1, title: 'Deploy', instruction: 'Load deploy script into Lab Terminal, run it, copy the address.', code: 'Step 2: Load deploy script → run in terminal' },
      { shared: true, title: 'Share address', instruction: 'Deployer shares contract address with partner (chat or out-of-band).' },
      { terminal: 1, title: 'Partner: Interact', instruction: 'Partner loads interact script, replaces address, runs it.', code: 'Step 4: Load interact script → edit address → run' },
      { shared: true, title: 'Verify', instruction: 'Both use Search Chain or terminal to verify contract state.', code: 'Search Chain or: await c.get()' },
    ],
    nuance: 'Uses embedded Lab Terminal. See CHAIN_INTERACTION_GUIDE.md for how to interact with the chain via code.',
  },
  {
    id: 'tokenization-lab',
    title: 'Tokenization Lab',
    doc: 'TOKENIZATION_LAB',
    duration: '60-75 min',
    difficulty: 'Intermediate',
    terminalsNeeded: 1,
    roles: 'Student (learner), Partner (for transfer/sale)',
    description: 'Read and explain ERC-721, deploy LabNFT, mint, trace, create metadata, transfer to a partner, and build an NFT-for-ETH sale contract.',
    steps: [
      { terminal: 1, title: 'Open Tokenization Lab', instruction: 'Go to Learning mode → Tokenization Lab in sidebar.', code: 'http://localhost:5173/?view=tokenization-lab' },
      { terminal: 1, title: 'Read & Explain', instruction: 'Step 1: Study the annotated ERC-721 contract and identify each function.', code: 'Step 1: Expand "What does this do?" for each function' },
      { terminal: 1, title: 'EVM Deep Dive', instruction: 'Step 2: Understand storage writes, gas costs, and event emission when mint() is called.', code: 'Step 2: Review EVM explanation panel' },
      { terminal: 1, title: 'Deploy & Mint', instruction: 'Load deploy script, run in Lab Terminal, then load mint script. Copy tx hash.', code: 'Step 3: Load deploy → mint → copy tx hash' },
      { terminal: 1, title: 'Trace Transaction', instruction: 'Paste tx hash into Search Chain to see sender, value, and Transfer event.', code: 'Step 3: Search Chain → paste tx hash' },
      { terminal: 1, title: 'Metadata & Data URI', instruction: 'Step 4: Create metadata JSON, generate data URI, use as tokenURI when minting.', code: 'Step 4: Metadata Builder → Generate Data URI → mint' },
      { terminal: 1, title: 'Transfer to Partner', instruction: 'Step 5: Get partner EOA address, load transfer script, replace addresses, run transferFrom.', code: 'Step 5: Load transfer script → paste addresses → run' },
      { terminal: 1, title: 'Build Sale Contract', instruction: 'Step 6: Deploy LabNFTSale. Seller: approve + list. Buyer: buy with ETH.', code: 'Step 6: Deploy → seller list → buyer buy' },
    ],
    nuance: 'Uses embedded Lab Terminal and ChainSearch. No 3rd party services. Transfer and sale require a partner (share addresses via Class Chat).',
  },
];

export const getLabById = (id) => LABS.find((l) => l.id === id);
