/**
 * Lab registry - source of truth for Available Labs.
 * Aligned with docs/*.md. Each lab has step-by-step instructions for Docker-first deployment.
 */

export const LABS = [
  {
    id: 'ransomware-investigation',
    title: 'Ransomware Investigation',
    doc: 'RANSOMWARE_INVESTIGATION_LAB',
    duration: '60-90 min',
    difficulty: 'Intermediate',
    terminalsNeeded: 2,
    roles: 'Investigator (student)',
    description: 'Trace a simulated ransomware payment through tumblers. Enter findings to validate against the scenario.',
    steps: [
      { terminal: 1, title: 'Enter container', instruction: 'Open a terminal and enter the Docker container.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 1, title: 'Go to CLI labs', instruction: 'Navigate to the forensics scripts.', code: 'cd /app/scripts/cli-labs/standalone' },
      { terminal: 1, title: 'Generate scenario (required)', instruction: 'Run setup first — the blockchain starts fresh each docker-compose up. This creates the victim, attacker, and tumbler addresses.', code: 'cd /app/scripts/cli-labs/standalone\nnode forensics-setup.js' },
      { terminal: 1, title: 'Run the lab', instruction: 'Launch the guided investigation lab.', code: 'cd /app/scripts/cli-labs/standalone\nnode 6-ransomware-investigation.js' },
      { terminal: 2, title: 'Open second terminal', instruction: 'Open a second terminal window for the Hardhat console (investigation commands).', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 2, title: 'Start Hardhat console', instruction: 'Use this terminal to run investigation commands when the lab prompts you.', code: 'npx hardhat console --network localhost' },
    ],
    nuance: 'You need TWO terminals: one for the lab prompts, one for running investigation commands. Switch between them as the lab directs.',
  },
  {
    id: 'ransomware-advanced',
    title: 'Ransomware Investigation (Advanced)',
    doc: 'RANSOMWARE_ADVANCED_LAB',
    duration: '90-120 min',
    difficulty: 'Intermediate',
    terminalsNeeded: 2,
    roles: 'Investigator (student)',
    description: 'Trace a multi-victim ransomware attack through a complex tumbler network. Builds on the basic lab.',
    steps: [
      { terminal: 1, title: 'Enter container', instruction: 'Open a terminal and enter the Docker container.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 1, title: 'Go to CLI labs', instruction: 'Navigate to the forensics scripts.', code: 'cd /app/scripts/cli-labs/standalone' },
      { terminal: 1, title: 'Generate advanced scenario (required)', instruction: 'Run setup first — creates 3 victims, multiple tumblers, and convergence points.', code: 'cd /app/scripts/cli-labs/standalone\nnode forensics-setup-advanced.js' },
      { terminal: 1, title: 'Run the advanced lab', instruction: 'Launch the multi-victim investigation.', code: 'cd /app/scripts/cli-labs/standalone\nnode 7-ransomware-advanced.js' },
      { terminal: 2, title: 'Open second terminal', instruction: 'Open a second terminal for the Hardhat console.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 2, title: 'Start Hardhat console', instruction: 'Use for investigation commands when prompted.', code: 'npx hardhat console --network localhost' },
    ],
    nuance: 'Two terminals required. Complete the basic Ransomware Investigation lab first.',
  },
  {
    id: 'house-sale',
    title: 'House Sale',
    doc: 'HOUSE_SALE_LAB',
    duration: '45-60 min',
    difficulty: 'Intermediate',
    terminalsNeeded: 3,
    roles: 'Admin, Seller (John), Buyer (Mark)',
    description: 'Simulate a real estate transaction. Three participants: Admin deploys, Seller and Buyer complete the escrow flow.',
    steps: [
      { terminal: 1, title: 'Admin: Enter container', instruction: 'Admin opens first terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 1, title: 'Admin: Deploy contract', instruction: 'Use CLI Contract Builder to deploy House Sale.', code: 'cd /app/scripts/cli-labs/standalone\nnode interactive.js\n# Select: 9. Contract Builder Lab → 1. House Sale' },
      { terminal: 2, title: 'Seller (John): Enter container', instruction: 'John opens a second terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 2, title: 'Seller: Open Hardhat console', instruction: 'John connects with his wallet.', code: 'npx hardhat console --network localhost' },
      { terminal: 3, title: 'Buyer (Mark): Enter container', instruction: 'Mark opens a third terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 3, title: 'Buyer: Open Hardhat console', instruction: 'Mark connects with his wallet.', code: 'npx hardhat console --network localhost' },
      { shared: true, title: 'Follow the lab flow', instruction: 'Admin shares contract address. John and Mark each create their OWN contract instance connected to their wallet. Follow the escrow steps: deposit → inspection → balance → confirm.' },
    ],
    nuance: 'THREE terminals (or three people with separate terminals). Each participant must create their own contract instance — do not share the same instance.',
  },
  {
    id: 'vehicle-title',
    title: 'Vehicle Title',
    doc: 'VEHICLE_TITLE_LAB',
    duration: '30-45 min',
    difficulty: 'Beginner',
    terminalsNeeded: 2,
    roles: 'Admin (DMV), Owners (students)',
    description: 'Register a vehicle title and transfer ownership. Learn asset provenance and ownership chains.',
    steps: [
      { terminal: 1, title: 'Admin: Enter container', instruction: 'Admin opens first terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 1, title: 'Admin: Deploy via CLI', instruction: 'Use Contract Builder → Vehicle Title Transfer.', code: 'cd /app/scripts/cli-labs/standalone\nnode interactive.js\n# Select: 9. Contract Builder Lab → 2. Vehicle Title Transfer' },
      { terminal: 2, title: 'Owner: Enter container', instruction: 'Each participant opens their own terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 2, title: 'Owner: Hardhat console', instruction: 'Connect and create contract instance with your wallet.', code: 'npx hardhat console --network localhost' },
    ],
    nuance: 'Multiple participants: open separate terminals with docker-compose exec for each (Admin, Owner 1, Owner 2, etc.).',
  },
  {
    id: 'event-tickets',
    title: 'Event Tickets',
    doc: 'EVENT_TICKETS_LAB',
    duration: '30-45 min',
    difficulty: 'Beginner',
    terminalsNeeded: 2,
    roles: 'Organizer, Attendees',
    description: 'Sell and manage event tickets. Limited supply, transfers, check-in, and refunds on cancellation.',
    steps: [
      { terminal: 1, title: 'Organizer: Enter container', instruction: 'Organizer opens first terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 1, title: 'Organizer: Deploy via CLI', instruction: 'Use Contract Builder → Event Tickets.', code: 'cd /app/scripts/cli-labs/standalone\nnode interactive.js\n# Select: 9. Contract Builder Lab → 3. Event Tickets' },
      { terminal: 1, title: 'Dashboard', instruction: 'Open dashboard to monitor sales.', code: 'http://localhost:5173/dashboard.html' },
      { terminal: 2, title: 'Attendees: Enter container', instruction: 'Each attendee opens their own terminal (or uses web UI).', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 2, title: 'Attendees: Hardhat console', instruction: 'Buy tickets, transfer, etc.', code: 'npx hardhat console --network localhost' },
    ],
    nuance: 'Dashboard at /dashboard.html for monitoring. Attendees can also use the web interface if available.',
  },
  {
    id: 'voting-system',
    title: 'Voting System',
    doc: 'VOTING_SYSTEM_LAB',
    duration: '30-45 min',
    difficulty: 'Beginner',
    terminalsNeeded: 2,
    roles: 'Election Admin, Voters',
    description: 'Multi-option election with time-limited voting and automatic winner determination.',
    steps: [
      { terminal: 1, title: 'Admin: Enter container', instruction: 'Admin opens first terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 1, title: 'Admin: Deploy via CLI', instruction: 'Use Contract Builder → Voting System.', code: 'cd /app/scripts/cli-labs/standalone\nnode interactive.js\n# Select: 9. Contract Builder Lab → 4. Voting System' },
      { terminal: 1, title: 'Dashboard', instruction: 'Open dashboard for results.', code: 'http://localhost:5173/dashboard.html' },
      { terminal: 2, title: 'Voters: Enter container', instruction: 'Each voter opens their own terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 2, title: 'Voters: Hardhat console', instruction: 'Cast votes.', code: 'npx hardhat console --network localhost' },
    ],
    nuance: 'Dashboard at /dashboard.html for live results.',
  },
  {
    id: 'crowdfunding',
    title: 'Crowdfunding',
    doc: 'CROWDFUNDING_LAB',
    duration: '45-60 min',
    difficulty: 'Intermediate',
    terminalsNeeded: 2,
    roles: 'Creator, Contributors',
    description: 'Launch a crowdfunding campaign. Goal-based triggers, contributions, refunds if goal not met.',
    steps: [
      { terminal: 1, title: 'Creator: Enter container', instruction: 'Creator opens first terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 1, title: 'Creator: Deploy via CLI', instruction: 'Use Contract Builder → Crowdfunding.', code: 'cd /app/scripts/cli-labs/standalone\nnode interactive.js\n# Select: 9. Contract Builder Lab → 5. Crowdfunding Campaign' },
      { terminal: 1, title: 'Dashboard', instruction: 'Monitor campaign progress.', code: 'http://localhost:5173/dashboard.html' },
      { terminal: 2, title: 'Contributors: Enter container', instruction: 'Each contributor opens their own terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 2, title: 'Contributors: Hardhat console', instruction: 'Contribute ETH, claim refunds if failed.', code: 'npx hardhat console --network localhost' },
    ],
    nuance: 'Dashboard for progress. Contributors need ETH to contribute.',
  },
  {
    id: 'classroom-vote',
    title: 'Classroom Vote',
    doc: 'CLASSROOM_VOTE_LAB',
    duration: '30-45 min',
    difficulty: 'Beginner',
    terminalsNeeded: 2,
    roles: 'Instructor (deployer), Students (voters)',
    description: 'Live voting on a class question. Instructor deploys, students vote, results displayed on dashboard.',
    steps: [
      { terminal: 1, title: 'Instructor: Enter container', instruction: 'Instructor opens first terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 1, title: 'Instructor: Deploy via CLI', instruction: 'Use Contract Builder → Classroom Voting Demo.', code: 'cd /app/scripts/cli-labs/standalone\nnode interactive.js\n# Select: 9. Contract Builder Lab → 6. Classroom Voting Demo' },
      { terminal: 1, title: 'Dashboard', instruction: 'Display results to class.', code: 'http://localhost:5173/dashboard.html' },
      { terminal: 2, title: 'Students: Enter container', instruction: 'Each student opens their own terminal (or uses web).', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 2, title: 'Students: Hardhat console', instruction: 'Vote using wallet.', code: 'npx hardhat console --network localhost' },
    ],
    nuance: 'Share instructor IP so students access dashboard at http://<INSTRUCTOR-IP>:5173/dashboard.html',
  },
  {
    id: 'token-concepts',
    title: 'Token Concepts (FT vs NFT)',
    doc: 'TOKEN_CONCEPTS_LAB',
    duration: '20-30 min',
    difficulty: 'Beginner',
    terminalsNeeded: 1,
    roles: 'Student (learner)',
    description: 'Learn fungible vs non-fungible tokens. Conceptual sections + optional hands-on deploy.',
    steps: [
      { terminal: 1, title: 'Enter container', instruction: 'Open a terminal.', code: 'docker-compose exec ethereum-trainer bash' },
      { terminal: 1, title: 'Run Token Concepts', instruction: 'Run the interactive lab (or use Learn tab in web app).', code: 'cd /app/scripts/cli-labs/standalone\nnode 8-token-concepts.js' },
      { terminal: 1, title: 'Alternative: Interactive menu', instruction: 'Or launch from main menu.', code: 'cd /app/scripts/cli-labs/standalone\nnode interactive.js\n# Select: 13. Token Concepts (FT vs NFT)' },
    ],
    nuance: 'Sections 1–3 are conceptual. Section 4 offers hands-on deploy (browser or CLI).',
  },
];

export const getLabById = (id) => LABS.find((l) => l.id === id);
